version: '2'

services:
  #Nginx Service
  webserver:
    build:
      context: dockerfile/webserver
    tty: true
    ports:
      - ${WEBSERVICE_HTTP_PORT}:80
    volumes:
      - ./:/project
  app:
    build:
      context: dockerfile/app
    depends_on:
      - db
    volumes:
      - .:/project
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - ${DB_PORT}:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

volumes:
  db: {}